### PR TITLE
Add .NET Core 3.0 support, deprecate all older versions

### PR DESCRIPTION
**Pull request by derwasp**
# Overview

This PR is moving the correlation tracking to the new undrelying driver: [System.Diagnostics.Activity](https://apisof.net/catalog/System.Diagnostics.Activity).

This class is not available in the older versions of the .NET framework and building a support for it doesn't make a lot of sense, at least at this stage.

A branch with the old version will stay there, if we decide that we need any support there: [net-framework](https://github.com/albumprinter/CorrelationTracking/tree/net-framework).

Since the .NET 3.1 support in available AWS Lambda since the beginning of the month, it is obvious that all the new applications will be using it to go forward. Most likely the old applications are going to be updated as well.

[.NET 3.0 has built-in support](https://devblogs.microsoft.com/aspnet/improvements-in-net-core-3-0-for-troubleshooting-and-monitoring-distributed-apps/) for correlation that requires 0 configuration to get it up and running. It automatically integrates with both incoming and outgoing requests.

This new standard allows for the usage if [W3C trace-context](https://www.w3.org/TR/trace-context), which we can kind of make backwards compatible with our format.

So what this PR does is effectively makes our solution connected to the new standardized version of distributed tracing, while keeping the backwards compatibility wherever possible.

# Proposed changes

* Added support for the Request-Response interceptors for the API requests: `CorrelationDiagnosticListenerSubscriber`.
* Added generic correlation logger `ActivityBagTagLoggerFactory` in the new package `Correlation.Logging` to decorate all the messages with any correlation-context data.
* Added forward compatibility support for http client calls via `CompatibleCorrelationHttpRequestDiagnosticListener`.
* Added support for [Microsoft.Extensions.Logging](https://www.nuget.org/packages/Microsoft.Extensions.Logging/)
* Move everything to `netstandard2.1`. See the compatibility table: [standard to .NET Core mapping](https://docs.microsoft.com/en-us/dotnet/standard/net-standard)
* Removed old .NET Framework support
* Removed [LibLog](https://github.com/damianh/LibLog) from most of the projects, since the project is deprecated and is not going to be supported anymore. `Extensions.Logging` should be used as a replacement.
As LibLog's author said, it seems like `Extensions.Logging` is _the standard_ and should be used in the .NET Core world. So it makes complete sense to move away from LibLog, which is no longer supported and use the standard library.

# Technical details

For the time being the new extension methods reside in the `Albelli.Correlation.Http.Server`. I haven't decided on the proper placement yet. But this can mean that this package will be the final place for the new extensions.

We always set the current `Activity.DefaultIdFormat` to `ActivityIdFormat.W3C`. This is required because the Microsoft's Hierarchical format can't be parsed as a `Guid` for the backwards compatibility with our old system.

This PR is only focused on the following things:
 * Adding the support for generic logging from the `System.Diagnostics.Activity`
 * Reading the old values to the new system to allow for backwards compatibility
 * Setting the values to the old http header, if this is required via `CompatibleCorrelationHttpRequestDiagnosticListener` (see [Example usage](#example-usage))
 * Adding support for the HTTP based transports. We are still relying on the old implementation for the SQS/SNS/RMQ transports.

This is PR is not:
 * Adding automatic support for all the transports (like SQS, SNS, Masstransit)

In order to be able to forward the correlation id from the _new systems_ to the _old systems_ it is still required to use the delegating handler that sets the `X-CorrelationId` header for the outgoing requests.

The new version allows us to pass along the correlation context with any arbitrary values. See the [article](https://devblogs.microsoft.com/aspnet/improvements-in-net-core-3-0-for-troubleshooting-and-monitoring-distributed-apps/) for details.

# Backward compatibility

**The code is only compatible with `netstandard2.1` (aka .NET Core 3) going forward.
This restrictions is there because the underlying transport is only working in the .NET Core 3, even though the interfaces are available in the previous versions.**

**The following protocol compatibility logic is in place:**

_Scenario 1_
A request with the old `X-CorrelationId` came in.

In this case we will try parsing the old `X-CorrelationId` and attempt to set it as the current `Activity`'s parent. Note that the `span-id` will be set to the predefined span `ffffffffffffffff` aka `EMPTY_SPAN` in the code.
This will allow us to have the current trace-id and root-id to be set to the old correlation id.

The old correlation values will also be added to the current `Activity`'s correlation context to be logged by the logger from the `Correlation.Logging` package.

_Scenario 2_
A request _without_ the old `X-CorrelationId` came in.
In this case the the current generated `trace-id` will be tried as a `Guid` for the old `X-CorrelationId`. If the parsing is not successful for whatever reason, a new `Guid` will be generated.

The old correlation values will also be added to the current `Activity`'s correlation context to be logged by the logger from the `Correlation.Logging` package.

_Scenario 3_
A request _with both_ ids: the old id and the new id came in.
In this case if the new id is in the W3C format, the old id will be ignored and the new id will take precedence.

In case the old id is not in the W3C format, it will be ignored and the new id will be generated.

# Example usage

## Reading incoming values

To get the backward compatiblity up and running in the .NET Core 3.x **server** application, the following code changes are required:

* Install the `Albelli.Correlation.Http.Server` package
* Add the decoration logger in the ConfigureServices block
* Add the diagnostic listener in the Configure block

```csharp
// ...

public void ConfigureServices(IServiceCollection services)
{
    // ...
    services.AddDefaultActivityBagTagLoggerFactory();
    // ...
}

// ...

public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
{
    app.UseCorrelationDiagnosticListenerSubscriber();
    // ...
}

```

By default the logger will enrich the log messages with all the Activity Tag elements and only Activity Tag elemens that start with a `X-` prefix. `AddDefaultActivityBagTagLoggerFactory` has an overload that accepts other conditions, should you desire to change it.

## Setting outgoing values automatically

**Please use this only if you absolutely need to, as otherwise the old standard will not go away. If you only need this for a single API call, please use the old delegating handlers**

To get the backward compatiblity up and running in the .NET Core 3.x **client** application that does **HTTP** calls, the following code changes are required:

* Install the `Albelli.Correlation.Http.Client` package
* Somewhere during the initialization process add `CompatibleCorrelationHttpRequestDiagnosticListener`

```csharp
// ...
DiagnosticListener.AllListeners.Subscribe(new CompatibleCorrelationHttpRequestDiagnosticListener());
//...
```

# Unrelated changes

* The nuget **symbol** packages are published in the new format: `snupkg`
* SourceLink for github is added. Now step-ins in visual studio will automatically download source code and allow for the breakpoints to be set
* CAKE version is updated to the version that supports VS2019

### CODE REVIEW

**Comment by derwasp** [comment]
For future references: how to add sources to pdbs: https://github.com/NuGet/docs.microsoft.com-nuget/issues/1278

**Comment by martijnmol** [comment]
Just asking, as PlantIT we still have several .net framework projects using this library. What is the reason for removing support for this?

**Comment by derwasp** [comment]
@martijnmol as the old binaries are not going to be removed and will still be available for installation, the ability to use all this in the new framework will not be affected.
However, the functionality that is going to be available after this PR is not possible to achieve with any stubs in the old .NET framework. The burden of keeping all these versions is just not worth the effort.

I have created a [branch](https://github.com/albumprinter/CorrelationTracking/tree/net-framework) based on the current master that will allow us to add any functionality that we need to the old packages.

This is the same approach I took for the 3.5 .NET support a few years ago. 3.5 was required just for 1 project and adding all the dependencies and workaround to master didn't seem like a good idea.


With all this said I am committed to keeping the backward protocol compatibility with the old versions of the packages.

Stay tuned, it's going to be amazing :)

**Comment by derwasp** [comment]
For future extensions, we should look at examples like this: https://github.com/SergeyKanzhelev/ot-demo-2019-11

**Comment by martijnmol** [comment]
@derwasp , when you are done, I think it would be cool to share this in the .NET guild, don't you think?

**Comment by derwasp** [comment]
@martijnmol there will definitely be a presentation about this, as I want to explain the whole concept and how it all works together.
But documentation and code first, demos second :

**Comment by martijnmol** [comment]
@derwasp awesome!

**Pull request merged**
