### PR TITLE
fix uselees nullable checks

### PR DESCRIPTION
**Pull request by rhamzatov**

### CODE REVIEW

**Comment by derwasp** [comment]
@rhamzatov Can you elaborate on why do you think we need this?

**Comment by derwasp** [comment]
As this property can indeed be null. And if it will be null at some point, you will be forced to chase the null reference exception.

**Comment by rhamzatov** [comment]
> As this property can indeed be null. And if it will be null at some point, you will be forced to chase the null reference exception.

It is actually not true. Current implementation https://github.com/damianh/LibLog/issues/96#issuecomment-174322863

**Comment by rhamzatov** [comment]
I believe this usage safer (as ResolveLogProvider will be called) and cleaner (shorter)

**Pull request merged**
